apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: givethbot-auth
data:
  bot_credentials.json: {{ .Values.botCredentials | b64enc }}
  client_secret.json: {{ .Values.clientSecret | b64enc }}
  credentials.json: {{ .Values.credentials | b64enc }}
