apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: givethbot-auth
data:
  bot_credentials.json: {{ .Values.botCredentials | quote }}
  client_secret.json: {{ .Values.clientSecret | quote }}
  credentials.json: {{ .Values.credentials | quote }}
