apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: givethbot-auth
data:
  bot_credentials.json: {{ .Values.botCredentials }}
  client_secret.json: {{ .Values.clientSecret }}
  credentials.json: {{ .Values.credentials }}
